### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by YAJATapps** [michelelacorte/FlickLauncher#11]
When I add a shortcut from opera to home screen and longclick on that shortcut the launcher crashes.

This is log of crash
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.ComponentName.getPackageName()' on a null object reference
03-30 20:55:58.864 E/AndroidRuntime( 7157): 	at com.android.launcher3.util.ShortcutsManager.getShortcutsBasedOnTag(ShortcutsManager.java:47)
03-30 20:55:58.864 E/AndroidRuntime( 7157): 	at com.android.launcher3.Launcher.onLongClick(Launcher.java:3290)
03-30 20:55:58.864 E/AndroidRuntime( 7157): 	at android.view.View.performLongClick(View.java:5243)
03-30 20:55:58.864 E/AndroidRuntime( 7157): 	at android.widget.TextView.performLongClick(TextView.java:9225)
03-30 20:55:58.864 E/AndroidRuntime( 7157): 	at com.android.launcher3.CheckLongPressHelper$CheckForLongPress.run(CheckLongPressHelper.java:41)
03-30 20:55:58.864 E/AndroidRuntime( 7157): 	at android.os.Handler.handleCallback(Handler.java:739)
03-30 20:55:58.864 E/AndroidRuntime( 7157): 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-30 20:55:58.864 E/AndroidRuntime( 7157): 	at android.os.Looper.loop(Looper.java:148)
03-30 20:55:58.864 E/AndroidRuntime( 7157): 	at android.app.ActivityThread.main(ActivityThread.java:5471)
03-30 20:55:58.864 E/AndroidRuntime( 7157): 	at java.lang.reflect.Method.invoke(Native Method)
03-30 20:55:58.864 E/AndroidRuntime( 7157): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
03-30 20:55:58.864 E/AndroidRuntime( 7157): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by michelelacorte** [comment]
You have to set package name in edit text, show me screenshot of your dialog. 

N.B
Shortcuts added by dialog isn't persistent, so if you restart launcher they disappear!

**Comment by YAJATapps** [comment]
I add link from opera like this
![screenshot_20170330-211355](https://cloud.githubusercontent.com/assets/17001098/24513041/d515dd4c-158d-11e7-95e0-abd260daad43.png)

It appeared on launcher
![screenshot_20170330-211556](https://cloud.githubusercontent.com/assets/17001098/24513153/1fccaf96-158e-11e7-9b52-35d0d8b2aa18.png)

When I long clicked it crashed (unfortunately ...)

They don't disappear on restart or crash. That log is of that crash only

**Comment by michelelacorte** [comment]
Maybe the shortcuts has brick..you must uninstall the launcher to reset preference...

**Comment by YAJATapps** [comment]
Tried that uninstalling reinstalling clearing data 
Still crashing on long clicking.
I think It is problem with shortcut manager.
Because when I am long clicking any other thing it is not crashing . and when I moved that shortcut to a folder then it not crashed on long click so it does not crash in folder because shortcuts are not opened in folder.

**Comment by michelelacorte** [comment]
Fixed! next update 0.1.0 Alpha 50
