### ISSUE TITLE
Removing the new pixel search bar?

### ISSUE THREAD

**Issue by n1had5** [michelelacorte/FlickLauncher#13]
How can I remove it? 
Perviously unticking the persistent search bar option in settings did it.

**Comment by michelelacorte** [comment]
I decided to disable this features temporarily because it causes bug..

**Comment by Lokesh-Krishna** [comment]
Could you at least please make it possible to remove the page housing this bar? I don't even have the Google app on my phone. Would love to be able to remove this.

**Comment by Lokesh-Krishna** [comment]
Can this issue be closed? The latest release has once again made it possible to remove the persistent search bar.
