### ISSUE TITLE
settings doesn't show up on android 6.0 devices  

### ISSUE THREAD

**Issue by TeamBrainStorm** [michelelacorte/FlickLauncher#15]
first off I want to say major kudos for making this launcher open source! when I run it on my android tablet it does not show the settings icon when you hold down on the home screen my tablet is running android 6.0.1 I look forward to seeing this launcher grow!

**Comment by michelelacorte** [comment]
Please attach screenshot

**Comment by YAJATapps** [comment]
See the hassettings method and where it Is used in launcher.java you will understand why it is not showing.
In launcher3 it only had allow rotation setting so it hides the button who don't need allow rotation

**Comment by michelelacorte** [comment]
@YAJATapps  You mean this:

`    protected boolean hasSettings() {
        if (mLauncherCallbacks != null) {
            return mLauncherCallbacks.hasSettings();
        } else {
            // On devices with a locked orientation, we will at least have the allow rotation
            // setting.
            return !getResources().getBoolean(R.bool.allow_rotation);
        }
    }`

it seems correct...

**Comment by YAJATapps** [comment]
I mean usage 

        // Bind settings actions
        View settingsButton = findViewById(R.id.settings_button);
        boolean hasSettings = hasSettings();
        if (hasSettings) {
            settingsButton.setOnClickListener(new OnClickListener() {
                @Override
                public void onClick(View view) {
                    if (!mWorkspace.isSwitchingState()) {
                        onClickSettingsButton(view);
                    }
                }
            });
            settingsButton.setOnLongClickListener(performClickOnLongClick);
            settingsButton.setOnTouchListener(getHapticFeedbackTouchListener());
        } else {
            settingsButton.setVisibility(View.GONE);
        }

Here in last second line you can see if has settings is not true then the button visibility is gone

**Comment by michelelacorte** [comment]
Ah thanks sir! I will fix

**Comment by TeamBrainStorm** [comment]
sorry for the late reply do you still want me to attach a screenshot? 

Please let me know :)

**Comment by michelelacorte** [comment]
No thanks!

**Comment by michelelacorte** [comment]
Fixed, next update 0.1.0 Alpha 54.. probably this evening!
