### ISSUE TITLE
Pages to the left? 

### ISSUE THREAD

**Issue by edent** [michelelacorte/FlickLauncher#16]
I normally have 5 pages with the centre one being my home screen. On Flick is there any way to do this - or does the home page have to be the left screen?

Thanks - love the launcher so far ☺️

**Comment by michelelacorte** [comment]
I'm sorry but the first page is locked... maybe in the future

**Comment by michelelacorte** [comment]
Done!

**Comment by edent** [comment]
Awesome! Will install tonight 😀

Thanks. Have a cookie 🍪
