### ISSUE TITLE
Searchbar bug

### ISSUE THREAD

**Issue by YAJATapps** [michelelacorte/FlickLauncher#19]
The searchbar overlaps the icons on portrait and in landscape it cuts when the row and columns are set to max.
Landscape
![screenshot_20170406-183256](https://cloud.githubusercontent.com/assets/17001098/24755992/d4eaa55c-1af9-11e7-8bde-113347b5dfb5.png)

Portrait
![screenshot_20170406-184925](https://cloud.githubusercontent.com/assets/17001098/24756009/e4fae470-1af9-11e7-9c4c-50a85c6c2f00.png)

**Comment by michelelacorte** [comment]
Thanks for the report!

**Comment by michelelacorte** [comment]
Fixed!
