### ISSUE TITLE
settings button is still not showing on tablets that are running android 6.0

### ISSUE THREAD

**Issue by TeamBrainStorm** [michelelacorte/FlickLauncher#21]
Hello I am still having the same issue where the launcher settings do not show up on tablets I am running the latest code on a nexus 7 as well as a samsung galaxy tab s 8.4 please look at the attached screenshot:

![screenshot_20170407-072211](https://cloud.githubusercontent.com/assets/5115315/24799885/43d2e132-1b63-11e7-9fe3-e2c35d77314d.png)

Once again thank you for all your hard work!

**Comment by YAJATapps** [comment]
After the fix ,source code is not updated on github. Maybe the play store version shows it.try that.

**Comment by YAJATapps** [comment]
It is fixed now close this issue.
