### ISSUE TITLE
Contact Widgets crash launcher

### ISSUE THREAD

**Issue by rohlandm** [michelelacorte/FlickLauncher#23]
I have a folder full of favorite contacts on my home screen. When I try to select one of them, Flick Launcher crashes and I get the recent apps overview.

**Comment by michelelacorte** [comment]
Please send me a report!

**Comment by rohlandm** [comment]
Unfortunately there is no "Flick Launcher has been stopped" message, it simply switches to the recent apps view and I have to start the launcher by using the home button (OnePlus 3, Android 7.1.1, OxygenOS 4.1.1), needing to choose which launcher to use (Flick or OnePlus) in the process.

I don't know if there is another way to send a report.

**Comment by rohlandm** [comment]
The last Update fixed the issue, thanks for your work :)
