### ISSUE TITLE
Desktop icons disappear after disabling the persistent search bar

### ISSUE THREAD

**Issue by gashole** [michelelacorte/FlickLauncher#24]
After disabling the persistent search bar, the desktop icons disappear, long-pressing the desktop stops working, and long-pressing the dock crashes the app.

App Version v0.1.0 Build 112
Android 7.0

**Comment by michelelacorte** [comment]
Please send me a report!

**Comment by Sashastav84** [comment]
yes? i have same problem. 
And the settings disappear when I remove the search whn i use long tap.

**Comment by michelelacorte** [comment]
I need some time to fix it..

**Comment by michelelacorte** [comment]
Fixed!
