### ISSUE TITLE
Apps dont block with fingerprint moto g4 plus

### ISSUE THREAD

**Issue by dvdetc1** [michelelacorte/FlickLauncher#29]
I cant lock apps in my moto g4 plus, I select the apps to lock but when I open the app it opens normal

**Comment by michelelacorte** [comment]
Do you have fingerprint registered? Otherwise can you tell me your android version

**Comment by dvdetc1** [comment]
ywa, I have a fingerprint registered in my device, and I have android 7

**Comment by kennyjackson19** [comment]
I have s7 edge,  only max of 3 apps are getting locked .the 4th app that we lock is getting opened normally.

**Comment by michelelacorte** [comment]
Fixed, wait next version (probably 0.1.0 Beta 152)
