### ISSUE TITLE
Appshortcut bug

### ISSUE THREAD

**Issue by YAJATapps** [michelelacorte/FlickLauncher#3]
![screenshot_20170328-104408](https://cloud.githubusercontent.com/assets/17001098/24390001/965a7bb2-13a3-11e7-80ab-a0d3dd5b5828.png)
This occurred with folder
When I clicked it open edit folder title dialog

![screenshot_20170328-104416](https://cloud.githubusercontent.com/assets/17001098/24390036/c5c0cc26-13a3-11e7-8959-785029869788.png)
This occurred with settings icon 
When I clicked it showed uninstall dialog

I am using android 6.0.1 and DPI is 220

**Comment by michelelacorte** [comment]
Thanks for report, I will fix soon!

**Comment by michelelacorte** [comment]
Fixed! This is the result:

![alt tag](https://s8.postimg.org/92m9c14g5/Shortcuts_Fix.png)
