### ISSUE TITLE
Notification count 

### ISSUE THREAD

**Issue by Sashastav84** [michelelacorte/FlickLauncher#30]
Sorry for my english)

When I receive a message in the status bar and open then it remains on the shortcut, even after reading!!!
And thanks for the launcher, I bought the pro version. I'm using the x86 processor and android 6. I'll wait for fixing the bugs because I like the launcher. Thank you.

**Comment by michelelacorte** [comment]
Thanks for your report, I cancel notification only when you enter app from home/drawer

**Comment by michelelacorte** [comment]
Solved?

**Comment by Sashastav84** [comment]
Yeah, all fine. thanks
