### ISSUE TITLE
Home button stops audio playback and mutes sound

### ISSUE THREAD

**Issue by rohlandm** [michelelacorte/FlickLauncher#31]
Since the last update (Alpha 124), Everytime the home button is used to go to the home screen audio playback is paused (tested with Spotify and pocketcast) and the volume is set to zero

**Comment by michelelacorte** [comment]
Have you a home button pro features enabled?

**Comment by rohlandm** [comment]
Both normal and long press are set to nothing in the pro features

**Comment by rohlandm** [comment]
I changed it to open notifications, but it did not solved the problem

**Comment by michelelacorte** [comment]
Have you tried to clear app data?

**Comment by rohlandm** [comment]
Yep, the problem persists

**Comment by michelelacorte** [comment]
Only with this two app right? Because I've tested on other app and everything works correctly...

**Comment by rohlandm** [comment]
The default music player of OnePlus OxygenOS does not pause, but the whole phone is muted (multimedia and ringtone/notifications). The other to tested players might have a function pausing the playback if the volume is muted, so the pause would not be an issue of the launcher but a reaction of the apps to it.

I tested the whole thing with the OnePlus launcher, which is not affected by this issue.

**Comment by michelelacorte** [comment]
Don't worry it is fixed! Google voice causes conflict with audio manager, wait next update 0.1.0 Alpha 126 probably!

**Comment by rohlandm** [comment]
Thank you, Great Work :)

**Comment by rohlandm** [comment]
Until the update is released the problem can be solved by deactivating the "Ok Google" recognition in the search settings

**Comment by michelelacorte** [comment]
Yes! Otherwise wait 10 min I pushed udpate now!
