### ISSUE TITLE
Unreadable text in all settings nested menus

### ISSUE THREAD

**Issue by notnsane** [michelelacorte/FlickLauncher#4]
Settings > Change grid size

Text is white on white. Same happens for all the nested menus.

**Comment by michelelacorte** [comment]
Which version of Android are running on phone?

**Comment by notnsane** [comment]
5.1!

**Comment by michelelacorte** [comment]
It is fixed?? I think yes!

**Comment by notnsane** [comment]
Still not fixed in latest Alpha, got you a screenshot. Not sure if it's my Android or my phone, but I don't have this issue in other apps (is the white color hardcoded?)

![screenshot_2017-04-03-22-57-41](https://cloud.githubusercontent.com/assets/7162375/24638967/ed4f2c78-18c2-11e7-9901-3913d0e5d81f.png)

**Comment by michelelacorte** [comment]
it looks strange, because if API < 23 then set dark theme!

**Comment by michelelacorte** [comment]
Fixed, next update 0.1.0 Alpha 100

![alt tag](https://s3.postimg.org/tvt4xul4j/Screenshot_1491689804.png)
