### ISSUE TITLE
App drawer lags

### ISSUE THREAD

**Issue by jerryn70** [michelelacorte/FlickLauncher#43]
I have installed 70 to 80 apps on my phone.
My app drawer settings is 5 x 5. When i scroll down and up the app drawer is laging.

**Comment by michelelacorte** [comment]
Can you provide me a video about this?

**Comment by jerryn70** [comment]
Sorry file size limit of github is only 10mb. So I can't upload. But plz believe me there is a lag

**Comment by michelelacorte** [comment]
I believe, I only want to see this.. can you upload on site?

**Comment by jerryn70** [comment]
Here https://www.mediafire.com/download/0hdcph936ssmj6b

**Comment by jerryn70** [comment]
Please inform me after viewing the video, so that I can remove that from my  MF drive .

**Comment by michelelacorte** [comment]
I have 105 app and it works correclty...and from video I don't see anything..
