### ISSUE TITLE
Allow us to change the search engine

### ISSUE THREAD

**Issue by notnsane** [michelelacorte/FlickLauncher#5]
For those of us that don't use the Google app (or have it uninstalled), we really need a way to search other engines (like DuckDuckGo or similar)

**Comment by michelelacorte** [comment]
Do you mean google search? Or app search?

**Comment by notnsane** [comment]
The persistent search bar on top of the home screen.

**Comment by michelelacorte** [comment]
You can remove this bar on settings menù!

**Comment by notnsane** [comment]
But I don't want to remove it, I want to actually use it. Currently I can't because I don't have the Google app installed. Maybe you can add more providers? It's just a type, and then launch browser.

**Comment by michelelacorte** [comment]
"It's just type, go, and then launch browser..." with which search engine ??

**Comment by Lokesh-Krishna** [comment]
If you are asking for one particular recommendation then I would like to suggest DuckDuckGo but you could add a setting that would let you pick between the major search engines (Google, Bing, Yahoo, Ask, DuckDuckGo, etc).

**Comment by michelelacorte** [comment]
In upcoming version:

![alt tag](https://s16.postimg.org/gyqzmmkmd/Screenshot_2017-04-10-16-42-13.png)

**Comment by michelelacorte** [comment]
Here is an example of bar:

![alt tag](https://s9.postimg.org/elbpzazv3/Screenshot_2017-04-10-17-00-16.png)

**Comment by michelelacorte** [comment]
Done, next update 0.1.0 Alpha 104 with

- Google
- Bing
- Yahoo
- Ask
- DuckDuckGo

Also with voice search
