### ISSUE TITLE
Icons are too small on first install

### ISSUE THREAD

**Issue by notnsane** [michelelacorte/FlickLauncher#6]
It seems like the "allow circular icons" setting makes all icons very small, it's not good for a "first impression". Make it opt-in?

**Comment by michelelacorte** [comment]
Which screen size do you have?
I can disable it by default in next update

**Comment by notnsane** [comment]
480 x 854 pixels, can't recall the DPI, but it's a little bigger than the default (240-280?)

**Comment by michelelacorte** [comment]
ok, I've disabled circular icon, and I've fixed shortcuts on 480x854 screen, see next update, I think 0.1.0 Alpha 22
