### ISSUE TITLE
Widget resizing

### ISSUE THREAD

**Issue by YAJATapps** [michelelacorte/FlickLauncher#7]
Allow widgets to be resized

Apply these two commits
https://github.com/SlimRoms/packages_apps_SlimLauncher/commit/7460c3b3f17a72f0bbe13e9227519fddc0b2fc66

https://github.com/YAJATapps/packages_apps_SlimLauncher/commit/b7106a71203d9d05a2760a89ce5f3e3bdc1a3b70

**Comment by michelelacorte** [comment]
Could you open pull request?

**Comment by YAJATapps** [comment]
Yes. I will open

**Comment by YAJATapps** [comment]
It is for few widgets not all for now
Try clock

**Comment by YAJATapps** [comment]
Opened pull request .
It will allow every to be scaled down to 1x1 and also which did not allowed are resized.

**Comment by michelelacorte** [comment]
It depends on widget...if widget support different size, than you can resize (through allowed size)

**Comment by YAJATapps** [comment]
After this commit it will not depend on widget.
I will send you a pic of a launcher on which I tried.

**Comment by michelelacorte** [comment]
Thanks for explanation!! Today I will merge it!

**Comment by YAJATapps** [comment]
Just see this
This was before commit not able to resize
![screenshot_20170330-131227](https://cloud.githubusercontent.com/assets/17001098/24492955/aef34444-154a-11e7-86ec-bfa51a4c041b.png)

These are after commit which are resized to max and min
![screenshot_20170330-131308](https://cloud.githubusercontent.com/assets/17001098/24492965/bd4ab748-154a-11e7-8cc0-4ff28d00939b.png)
![screenshot_20170330-131227](https://cloud.githubusercontent.com/assets/17001098/24493007/e3f76fc6-154a-11e7-8fac-0def40053e8f.png)

**Comment by michelelacorte** [comment]
Nice work!

**Comment by YAJATapps** [comment]
![screenshot_20170330-131311](https://cloud.githubusercontent.com/assets/17001098/24493057/0b306962-154b-11e7-8561-1245621629de.png)
Last one was by chance this is it which I wanted to send

**Comment by YAJATapps** [comment]
So now when we can make widgets 1x1 .
So one feature request- to allow widgets in the dock.

**Comment by michelelacorte** [comment]
Yes! Thanks sir! Just wait for official update on Google Play!
