### ISSUE TITLE
Unable to re-enable Persistent Search Bar

### ISSUE THREAD

**Issue by nerdicus** [michelelacorte/FlickLauncher#8]
I disabled the persistent search bar to have more room on my home screen, but ended up wanting it back. Tried to Re-Enable persistent search bar, and the launcher restarts without adding it back to the homescreen.

**Comment by michelelacorte** [comment]
Thanks for reporting, I will fix soon!!

**Comment by michelelacorte** [comment]
It is fixed?

**Comment by Lokesh-Krishna** [comment]
Can confirm that on my device (OnePlus One, running Android 7.1.1) it is possible to disable and then again enable the persistent search bar.
